// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Services.proto
// Protobuf C++ Version: 5.29.5

#include "Services.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Services_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Services_2eproto = nullptr;
const ::uint32_t TableStruct_Services_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_Services_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016Services.proto\022\010protobuf\032\025Message2Clie"
    "nts.proto\032\024Message2Server.proto2\257\010\n\020Avai"
    "lableService\0223\n\rTryConnection\022\017.protobuf"
    ".IDMsg\032\021.protobuf.BoolRes\022L\n\017RegisterFac"
    "tory\022\034.protobuf.RegisterFactoryMsg\032\031.pro"
    "tobuf.MessageToClient0\001\0227\n\006GetMap\022\025.prot"
    "obuf.NullRequest\032\026.protobuf.MessageOfMap"
    "\022,\n\004Move\022\021.protobuf.MoveMsg\032\021.protobuf.M"
    "oveRes\0222\n\007Recover\022\024.protobuf.RecoverMsg\032"
    "\021.protobuf.BoolRes\0223\n\007Harvest\022\025.protobuf"
    ".ResourceMsg\032\021.protobuf.BoolRes\0220\n\006Attac"
    "k\022\023.protobuf.AttackMsg\032\021.protobuf.BoolRe"
    "s\0220\n\006Occupy\022\023.protobuf.OccupyMsg\032\021.proto"
    "buf.BoolRes\022,\n\004Send\022\021.protobuf.SendMsg\032\021"
    ".protobuf.BoolRes\022,\n\004Load\022\021.protobuf.Loa"
    "dMsg\032\021.protobuf.BoolRes\022.\n\005Trade\022\022.proto"
    "buf.TradeMsg\032\021.protobuf.BoolRes\022B\n\017Creat"
    "eCharacter\022\034.protobuf.CreateCharacterMsg"
    "\032\021.protobuf.BoolRes\022O\n\022CreateCharacterRI"
    "D\022\034.protobuf.CreateCharacterMsg\032\033.protob"
    "uf.CreatCharacterRes\0227\n\007Produce\022\031.protob"
    "uf.ProduceGoodsMsg\032\021.protobuf.BoolRes\022:\n"
    "\013UplevelTech\022\030.protobuf.UplevelTechMsg\032\021"
    ".protobuf.BoolRes\0222\n\014EndAllAction\022\017.prot"
    "obuf.IDMsg\032\021.protobuf.BoolRes\022D\n\005AskAI\022\034"
    ".protobuf.StrategicAIRequest\032\035.protobuf."
    "StrategicAIResponse\022T\n\025GetCurrentEventSt"
    "atus\022\034.protobuf.EventStatusRequest\032\035.pro"
    "tobuf.EventStatusResponseb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Services_2eproto_deps[2] =
    {
        &::descriptor_table_Message2Clients_2eproto,
        &::descriptor_table_Message2Server_2eproto,
};
static ::absl::once_flag descriptor_table_Services_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Services_2eproto = {
    false,
    false,
    1153,
    descriptor_table_protodef_Services_2eproto,
    "Services.proto",
    &descriptor_table_Services_2eproto_once,
    descriptor_table_Services_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_Services_2eproto::offsets,
    file_level_enum_descriptors_Services_2eproto,
    file_level_service_descriptors_Services_2eproto,
};
namespace protobuf {
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Services_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
